Catalogue Entries V1
VOREStation/VOREStation pull request #10222
Opened 2021-04-27 16:50 UTC by klaasjared

Adds Cataloguer lore that needed to be done for a while now...

Lore that was added
-Deathclaw
-Fennec
-Giant Frog

2021-04-27 16:55 UTC, Novacat requested changes
Wait these guys had cataloguer entries?

oh.

Someone forgot to add:
catalogue_data = list(/datum/category_item/catalogue/fauna/giant_spider/guard_spider)
(as an example)

To all the virgo voremobs vars. Can you do that please?

2021-04-27 18:36 UTC, Novacat approved these changes

2021-04-27 18:38 UTC, Novacat submitted a review, later dismissed
Actually, I would like the spaces on the start of new lines to be converted into tabs instead

2021-04-27 19:46 UTC, TheFurryFeline reviewed
Spelling fixes suggestions, but silly browser is preventing me from being able to do tabs that don't just go right to a button and out of the typing section, pfft.

2021-04-27 19:46 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/rat.dm
> +	It is unclear what experiment caused this species to grow to such an unnatural size, however it hasn't effected the rat's \
```suggestion
	It is unclear what experiment caused this species to grow to such an unnatural size, however it hasn't affected the rat's \
```

2021-04-27 19:46 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/rat.dm
> +	general docile nature. When encounterd by human's or other species it generally ignores them unless provoked.\
```suggestion
	general docile nature. When encounterd by humans or other species it generally ignores them unless provoked.\
```

2021-04-27 19:46 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/frog.dm
> +	Modern day Giant Frogs have reveted to a more feral state compared to their original anncestors and are hostile \
```suggestion
	Modern day Giant Frogs have reverted to a more feral state compared to their original ancestors and are hostile \
```

2021-04-27 19:46 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/frog.dm
> +    These animals, are considered an invasive species, and thus hunters are encouraged to hunt them."
Tab indent here, not spaces.

2021-04-27 19:46 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/animal/space/snake_vr.dm
> +    Severe consequences may result in violation of this order."
Tab indent here, not spaces.

2021-04-27 19:46 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/deathclaw.dm
> +	The creatures are known to attack humans and other animals regularly to protect their territoy \
```suggestion
	Originally the Deathclaw was a top secret genetics project run by a now defunct defence company lost to time.\
	The creatures are known to attack humans and other animals regularly to protect their territory \
```

2021-04-27 19:46 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/snake.dm
> +    dealt with in a professional manner."
Tab indents

2021-04-27 19:46 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/snake.dm
> +	This particular species of snake has likely been mutated by the many phoron deposites in the region and \
```suggestion
	This particular species of snake has likely been mutated by the many phoron deposits in the region and \
```

2021-04-27 22:51 UTC, TheFurryFeline reviewed
Moar spelling fixies <3

2021-04-27 22:51 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/sect_queen.dm
> +	inconsistent. A Sect Queen can vary from hositle to docile depending on certain factors that scientists have \
```suggestion
	inconsistent. A Sect Queen can vary from hostile to docile depending on certain factors that scientists have \
```

2021-04-27 22:51 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/sect_drone.dm
> +	allowing the drone to carry multiple large prey inside of its stomach with realitive ease."
```suggestion
	inconsistent. A Sect Drone can vary from hostile to docile depending on certain factors that scientists have \
	yet to uncover. \
	<br>\
	The lack  of chitin on the underside of its abdomen is deliberate, as the flesh is very elastic and stretchable, \
	allowing the drone to carry multiple large prey inside of its stomach with relative ease."
```

2021-04-28 16:49 UTC, Novacat commented
Going to wait for the Loremins to review this.

2021-04-28 19:05 UTC, TheFurryFeline reviewed
Seems a commit undid the spell fixes here. Be sure to keep your branch synched.

2021-04-28 19:05 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/sect_drone.dm
> +	allowing the drone to carry multiple large prey inside of its stomach with realitive ease."
```suggestion
	inconsistent. A Sect Drone can vary from hostile to docile depending on certain factors that scientists have \
	yet to uncover. \
	<br>\
	The lack  of chitin on the underside of its abdomen is deliberate, as the flesh is very elastic and stretchable, \
	allowing the drone to carry multiple large prey inside of its stomach with relative ease."
```

2021-04-28 19:05 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/sect_queen.dm
> +	inconsistent. A Sect Queen can vary from hositle to docile depending on certain factors that scientists have \
```suggestion
	inconsistent. A Sect Queen can vary from hostile to docile depending on certain factors that scientists have \
```

2021-05-05 23:39 UTC, Novacat requested changes
The Loremins have taken a quick peek:

On the snakes :

These animals are a protected species and are not to be harmed, hunted, or captured by anyone. \
    Severe consequences may result in violation of this order."

No. We're not going to make people think getting a pet snake or something is going to be punished. I want that paragraph removed.


On the Fennecs :

Their presence on Virgo 4 spans back to when the colony was first established and now modern Virgo \
    Fennec are upwards of five times larger than their Sol cousins and have gained a larger appetite. \
    However, despite this they are passive and do not actively hunt as their bodies have grown accustomed \
    to less available food sources.\


Not... Really? I would make them more a case of convergent evolution who actually have little to do with Earth fennecs all that much.

These animals, despite their current Conservation status, are a protected species and are not to be \
    harmed, hunted, or captured by anyone. Severe consequences may result in violation of this order."

Again, no.


On the Giant Snakes :

This particular species of snake has likely been mutated by the many phoron deposits in the region and \
    has grown to an unnatural size. 

Not sure Virgo 4 maps have Phoron. Deliberate gene manipulation might be more the reason.


On the Deathclaw :

Originally the Deathclaw was a top secret genetics project run by a now defunct defence company lost to time.\
    The creatures are known to attack humans and other animals regularly to protect their territory \
    or to hunt for food. It is speculated that they escaped roughly around the time the Hegemony War \
    broke out as sighting of these beasts in the wild began around that time. \


They are a result of gene manipulation, but not from any company or human hand, but rather the ancestors of the Zorren. That lil' tidbit isn't known, but they do share the same genetic "signs" of Zorren.

2021-05-07 22:30 UTC, Novacat approved these changes

2021-05-07 22:40 UTC, TheFurryFeline reviewed
One last round of spellchecks, yay.

2021-05-07 22:40 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/frog.dm
> +	These Giant Frogs are decendants from scientific frogs that were used for study during the great Sol Expansion Period. \
```suggestion
	the order Anura. This specific species - Anura gigantus - is a mutated form of Frogs, largely due to exposure to mutagen chemicals. \
	These Giant Frogs are descendants from scientific frogs that were used for study during the great Sol Expansion Period. \
```

2021-05-07 22:40 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/fennec.dm
> +	have a larger appetite. Thier diet mainly consists of whatever small creatures that they manage to scrounge from \
```suggestion
	a separate evolutional path. Virgo Fennec are upwards of five times larger than their Sol cousins and consequently \
	have a larger appetite. Their diet mainly consists of whatever small creatures that they manage to scrounge from \
```

2021-05-07 22:40 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/rat.dm
> +	general docile nature. When encounterd by humans or other species it generally ignores them unless provoked.\
```suggestion
	but stereotypical rats are found in the genus Rattus. This specific species of rat is a mutated descendant from lab rats. \
	It is unclear what experiment caused this species to grow to such an unnatural size, however it hasn't affected the rat's \
	general docile nature. When encountered by humans or other species it generally ignores them unless provoked.\
```

2021-05-07 22:40 UTC, TheFurryFeline commented on code/modules/mob/living/simple_mob/subtypes/vore/rat.dm
> +	disposals or areas that have large amounts of live food (other rats, mice, etc.) such as maint tunnels. \
```suggestion
	disposals or areas that have large amounts of live food (other rats, mice, etc.) such as maintenance tunnels. \
```

2021-05-07 23:21 UTC, merged