Map Polish
VOREStation/VOREStation pull request #10539
Opened 2021-06-02 07:35 UTC by VictorZisthus

SURFACE 1
Fixed a floating Medbay Intercom in First-Aid

Made structural pillars r-wall instead of regular wall in case Kenzie Houser ventures to the supported area.

Added R-wall to the Virology airlock. That lockdown blast door isn't gonna stop anyone if they can just go around it with ease.

Gave the clown a bit more love [and materials in their little storage room]

Added Security cameras to Mental Health. Switched the locations of the trash bin and chemical closet.

Added more scrubbers to Tram Station for faster atmos fixes.

Removed an odd section of r-wall from brig storage.

Fixed holodeck lighting issue by adding APC's.

SURFACE 2
Continued pillar r-wall from S1

Removed access requirements on Resleeving Washroom.

SURFACE 3
Sectioned off the Tether Shuttle pads with emergency airlocks, scrubbers, and vents. Added more parachutes to accommodate a full Tour Bus and crew plus hide new scrubbers a bit.

Cleaned up the oil in the robotic operating rooms. We all know that nobody uses them enough for them to warrant them being dirty all the time.

ASTEROID
Fixed Tcommsat inner airlock, removed redundant turret control switch. Fixed primary airlock.

MINING
Added missing emergency shutters. Gave Engineering and atmospherics access to the outer airlock and utility room.

SOLARS
Adjusted door access for atmos room and the room with heavy scrubber control console. Fixed a wonky intercom. Added EOD stuff. Rearranged the Toxins workroom and gave it chem-nade capabilities.

FILES
Added the Toxins football, a unique and robust secure briefcase for Toxins!

2021-06-02 07:38 UTC, SigholtStarsong commented
Just to ask, the security camera is not directly in the psychiatrists' office, correct?_

2021-06-02 07:47 UTC, SigholtStarsong commented
I'd personally say that probably violates a patient's right to privacy,
given how sensitive mental health can be.

On Wed, Jun 2, 2021, 2:39 AM Victor Zisthus ***@***.***>
wrote:

> Just to ask, the security camera is not directly in the psychiatrists'
> office, correct?_
>
> It is actually. That a bad thing?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/VOREStation/VOREStation/pull/10539#issuecomment-852815152>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD5YL2RMS6G32J6FBS53MHDTQXN2VANCNFSM456F32FQ>
> .
>

2021-06-03 18:05 UTC, Novacat requested changes

2021-06-03 18:05 UTC, Novacat commented on code/game/objects/items/weapons/storage/secure_vr.dm
> +	force = 14 // DON'T FUCK WITH THE SCIENCE TEAM!
tbh if it is going to have more force, it probably should have slowdown as well.

2021-06-04 17:17 UTC, Novacat submitted a review, later dismissed
The air pump changes have me a bit worried in the sense of "I have no idea how this works and I am afraid this change might break things elsewhere"

2021-06-04 17:17 UTC, Novacat commented on code/game/objects/items/weapons/storage/secure_vr.dm
> +	slowdown = 0.25
Slowdown should be done in intervals of 0.5

2021-06-04 22:43 UTC, VictorZisthus commented
> 
> 
> The air pump changes have me a bit worried in the sense of "I have no idea how this works and I am afraid this change might break things elsewhere"

I... Don't follow?

It's the only way I've seen to get the huge air pumps going again. Inheritance ensures that with the commented-out code the huge pumps will act just like the little ones, and in my vigorous testing that seems to be the case.

2021-06-04 23:24 UTC, VictorZisthus commented
Regarding the code change I made disabled a VR override on an atmos code item that intentionally disables a feature that I can't fathom a reason for being disabled in the first place.

I'm assuming it was disabled so that random non-atmosians couldn't walk up and fuck with it, which is an entirely valid concern, but since the computers that they are supposed to use do not exist... All that line of code does is completely lock out access to the device entirely. If it's not pre-mapped to do something or VV'd then you can't change it's settings AT ALL.

2021-06-22 15:54 UTC, Novacat requested changes
Conflict.

2021-06-24 00:57 UTC, VictorZisthus commented
Gotcha! Gonna fix that tomorrow

2021-07-03 20:11 UTC, Arokha commented
Even more merge conflicts!

2021-07-03 22:34 UTC, VictorZisthus commented
> Even more merge conflicts!

*scream*

I'll look into it on Monday or Tuesday XD

2021-07-04 02:05 UTC, TheFurryFeline commented
Part of it's my bad because I snuck in a filename rename for the latter two map files, lmao.

2021-07-07 22:15 UTC, VictorZisthus commented
Ok, I don't understand where the conflict is coming from at all.

2021-07-26 19:35 UTC, VictorZisthus commented
Probably gonna have to redo this whole PR when I get the chance, lol

2021-08-01 15:38 UTC, Arokha commented
Okiedoke.

2021-08-01 15:38 UTC, closed without merging