Pandora029 fluff item
VOREStation/VOREStation pull request #10635
Opened 2021-06-13 21:08 UTC by PastelPrinceDan

https://forum.vore-station.net/viewtopic.php?f=27&t=1986

2021-06-14 19:37 UTC, Novacat requested changes

2021-06-14 19:37 UTC, Novacat commented on code/modules/vore/fluffstuff/custom_clothes_vr.dm
> +	armor = list(melee = 25, bullet = 20, laser = 20, energy = 15, bomb = 20, bio = 0, rad = 0) //same as other sec coats
This is redundant if it is a subtype of security coats. You can safely delete this line.

2021-06-14 19:37 UTC, Novacat commented on code/modules/vore/fluffstuff/custom_clothes_vr.dm
> +	var/owner = "pandora029"
Delete this, since it will throw an unused var error every time it compiles.

2021-06-14 19:37 UTC, Novacat commented
Keep in mind that it will inherit the properties of all of its parent objects. Has this been tested?

2021-06-14 22:10 UTC, PastelPrinceDan commented
> Keep in mind that it will inherit the properties of all of its parent objects. Has this been tested?

right, removed the two lines. 
i tested it on a private server and everything worked fine yeah

2021-06-20 17:39 UTC, Novacat approved these changes

2021-06-20 17:39 UTC, merged