[DNM] [WIP] TGUI 4.3
VOREStation/VOREStation pull request #10636
Opened 2021-06-13 23:24 UTC by ShadowLarkens

I'm putting this up because I need help reviewing it. This update was performed using the "replace the TGUI folder" approach, and this means that a lot of properties on components and .scss file tweaks were wiped out, rendering a number of our UIs subtly but annoyingly different. I need to go through each changed file and look for changes like this:
![https://i.tigercat2000.net/2021/06/firefox_Swv9AbIbdx.png](https://i.tigercat2000.net/2021/06/firefox_Swv9AbIbdx.png) ![https://i.tigercat2000.net/2021/06/firefox_u6d8DkPget.png](https://i.tigercat2000.net/2021/06/firefox_u6d8DkPget.png)

The linter can't tell us about missing properties, but they will nevertheless cause issues. Basically, we need to check for reversions.

2021-06-13 23:26 UTC, ShadowLarkens commented on tgui/packages/tgui/package.json
> +    "prop-types": "^15.7.2",
We can get rid of this and it's usage

2021-06-13 23:31 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/layouts/Window.scss
> +  height: 100%;
may be causing issues

2021-06-13 23:31 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/layouts/Layout.scss
> -.Layout__content--flexRow {
Regression

2021-06-13 23:33 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/Tabs.scss
> +/**
Unidentified regression in this file causing icon-only tabs to look weird

2021-06-13 23:34 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/Section.scss
> -.Section--flex {
Regression

2021-06-13 23:34 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/Section.scss
> +  position: relative;
Regression

2021-06-13 23:34 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/Section.scss
> -.Section--scrollable .Section__content {
Regression

2021-06-13 23:34 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/Section.scss
> -.Section__content--noTopPadding {
Regression

2021-06-13 23:35 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/Section.scss
> -.Section__content--stretchContents {
Regression

2021-06-13 23:35 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/Section.scss
> -.Section--level--2 .Section__titleText {
Regressions on level

2021-06-13 23:35 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/Section.scss
> -  flex-grow: 1;
Potential issue

2021-06-13 23:36 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/LabeledList.scss
> -.LabeledList__breakContents {
regression

2021-06-13 23:36 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/Knob.scss
> -.Knob__popupValue--right {
regression?

2021-06-13 23:37 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/Flex.scss
> -  display: block !important;
potential issue

2021-06-13 23:37 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/Dropdown.scss
> -  padding-left: 0.5em;
potential issue

2021-06-13 23:39 UTC, ShadowLarkens commented on tgui/packages/tgui/routes.js
> -export const routingError = (type, name) => () => {
Regression

2021-06-13 23:40 UTC, ShadowLarkens commented on tgui/packages/tgui/layouts/Window.js
> -    refocusLayout();
Regression

2021-06-13 23:41 UTC, ShadowLarkens commented on tgui/packages/tgui/layouts/Window.js
> -      resizable,
All windows are now resizable without consideration, this property is deprecated and needs to be removed from interfaces

2021-06-13 23:41 UTC, ShadowLarkens commented on tgui/packages/tgui/layouts/NtosWindow.js
> -            refocusLayout();
Regression

2021-06-13 23:41 UTC, ShadowLarkens commented on tgui/packages/tgui/layouts/NtosWindow.js
> +                lineHeight="22px"
Undesired

2021-06-13 23:42 UTC, ShadowLarkens commented on tgui/packages/tgui/format.js
> -export const formatCommaNumber = value => {
Regression

2021-06-13 23:44 UTC, ShadowLarkens commented on tgui/packages/tgui/constants.js
> -export const T0C = 273.15;
Regression

2021-06-13 23:44 UTC, ShadowLarkens commented on tgui/packages/tgui/constants.js
>  export const RADIO_CHANNELS = [
Regression

2021-06-13 23:44 UTC, ShadowLarkens commented on tgui/packages/tgui/constants.js
>  const GASES = [
Regression

2021-06-13 23:45 UTC, ShadowLarkens commented on tgui/packages/tgui/components/Tabs.js
> -import { classes } from 'common/react';
Something about these changes are fucky, investigate

2021-06-13 23:46 UTC, ShadowLarkens commented on tgui/packages/tgui/components/Section.js
> -    noTopPadding,
Regression

2021-06-13 23:46 UTC, ShadowLarkens commented on tgui/packages/tgui/components/Section.js
> -    stretchContents,
Regression

2021-06-13 23:46 UTC, ShadowLarkens commented on tgui/packages/tgui/components/Section.js
> -    level = 1,
Regression

2021-06-13 23:47 UTC, ShadowLarkens commented on tgui/packages/tgui/components/Modal.js
> -  let handleKeyDown;
Regression

2021-06-13 23:47 UTC, ShadowLarkens commented on tgui/packages/tgui/components/LabeledList.tsx
> -    verticalAlign,
Regression

2021-06-13 23:47 UTC, ShadowLarkens commented on tgui/packages/tgui/components/LabeledList.tsx
> -    ...rest
Regression

2021-06-13 23:48 UTC, ShadowLarkens commented on tgui/packages/tgui/components/Flex.tsx
> -      'align-content': alignContent,
Regression

2021-06-13 23:49 UTC, ShadowLarkens commented on tgui/packages/tgui/components/Dropdown.js
> -    if (placeholder) {
Regression

2021-06-13 23:49 UTC, ShadowLarkens commented on tgui/packages/tgui/components/Dropdown.js
> -      maxHeight,
Regression

2021-06-13 23:49 UTC, ShadowLarkens commented on tgui/packages/tgui/components/Dropdown.js
> -      placeholder,
Regression

2021-06-13 23:50 UTC, ShadowLarkens commented on tgui/packages/tgui/components/Button.js
> -    iconSize,
Regression

2021-06-13 23:50 UTC, ShadowLarkens commented on tgui/packages/tgui/components/Button.js
> -    tooltipScale,
Regression

2021-06-13 23:50 UTC, ShadowLarkens commented on tgui/packages/tgui/components/Box.tsx
> -  order: mapRawPropTo('order'),
Lot of regressions in this file

2021-06-13 23:52 UTC, ShadowLarkens commented on tgui/packages/common/string.js
> +    currentStr = currentStr.replace(regex, str => str.toLowerCase());
Regression

2021-06-13 23:53 UTC, ShadowLarkens commented on tgui/docs/writing-tests.md
> +## Jest
TODO: Add to CI

2021-06-13 23:53 UTC, ShadowLarkens commented on tgui/docs/tutorial-and-examples.md
> -tgui_interact(mob/user, ui_key)
Rename Regressions

2021-06-13 23:53 UTC, ShadowLarkens commented on tgui/docs/converting-old-tgui-interfaces.md
> +# Converting old tgui interfaces to tgui-next
Need to steal nano-to-tgui back and put it as an additional resource

2021-06-13 23:54 UTC, ShadowLarkens commented on tgui/docs/component-reference.md
> -- `level: number` - Section level in hierarchy. Default is 1, higher number
Regression

2021-06-13 23:56 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/Section.scss
> -.Section--level--2 .Section__titleText {
Irrelevant, see component guide about Section

2021-06-13 23:58 UTC, ShadowLarkens commented on code/modules/tgui/external.dm
> +		if(!check_rights(R_ADMIN) || usr.client.tgui_cache_reloaded)
Regression, admin only perms on dev server is a false sense of security change

2021-06-14 00:06 UTC, ShadowLarkens commented
also I really need to make sure to document all of these changes this time

2021-06-14 03:29 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/Tabs.scss
> +/**
Tabs.Tab now supports an `icon` property which should be used instead of <Icon> inside of a <Tabs.Tab>'s content.

2021-06-15 00:39 UTC, ShadowLarkens commented on tgui/packages/tgui/styles/components/Knob.scss
> -.Knob__popupValue--right {
no

2021-06-15 00:39 UTC, ShadowLarkens commented on tgui/packages/tgui/layouts/Window.js
> -      resizable,
meh it doesn't hurt to keep it around, file change bloat

2021-06-15 00:39 UTC, ShadowLarkens commented on tgui/packages/tgui/layouts/NtosWindow.js
> +                lineHeight="22px"
Works actually

2021-06-15 00:48 UTC, ShadowLarkens commented on tgui/packages/tgui/components/Button.js
> -    tooltipScale,
unused and unsupported by popper

2021-06-15 01:27 UTC, ShadowLarkens commented
This is now ready.

2021-06-15 03:24 UTC, SplinterGP requested changes

2021-06-15 03:24 UTC, SplinterGP commented on tgui/packages/tgfont/.gitignore
> +/dist
you don't want this if youre not using CBT

2021-06-18 04:22 UTC, merged