Makes time/tram use REALTIMEOFDAY rather than world.time
VOREStation/VOREStation pull request #10946
Opened 2021-07-07 06:30 UTC by MarinaGryphon

REALTIMEOFDAY means that at 11:59:59 -> 12:00:00, the time will go from 864000 to 864001 (Or 863999 to 864000?) and continue. Basically, it takes into account midnight rollover and is strictly monotonic.
Needs testing. I can't really just... AFK on a local server for 6 hours, so like... Iunno.

2021-07-07 06:48 UTC, MarinaGryphon commented
Did local testing by changing my system time, tram was in fact called exactly six hours after roundstart.

2021-07-07 13:11 UTC, Little-119 commented
Wait, what happens without this? Like what does this fix? Asking out of curiosity, mostly

2021-07-07 15:47 UTC, Arokha commented
I have *some concerns* about this, since I see that subsystems use REALTIMEOFDAY and yet at 8pm (my time zone) every day if the server is starting, you'll end up with zany results like the server reporting 864000+ seconds to do subsystem init.

2021-07-07 17:41 UTC, Arokha requested changes
This is not monotonic, and will break shift lengths significantly, resulting in shifts that may never end, despite the 'test'. These macros aren't complete. `rollovercheck_last_timeofday` is never set anywhere, despite being checked in various spots by this macro. That's why this is broken at 00:00:00 GMT (8pm my time) for subsystem inits which report zany times for their startups.


```
#define MIDNIGHT_ROLLOVER		864000
#define REALTIMEOFDAY (world.timeofday + (MIDNIGHT_ROLLOVER * MIDNIGHT_ROLLOVER_CHECK))
#define MIDNIGHT_ROLLOVER_CHECK ( rollovercheck_last_timeofday != world.timeofday ? update_midnight_rollover() : midnight_rollovers )

/var/midnight_rollovers = 0
/var/rollovercheck_last_timeofday = 0
/proc/update_midnight_rollover()
	if (world.timeofday < rollovercheck_last_timeofday)
		return midnight_rollovers++
	return midnight_rollovers
```

world.timeofday will be 0 at 00:00:00 gmt, REALTIMEOFDAY will be...
`(0 + (864000 * MIDNIGHT_ROLLOVER_CHECK)`
while MIDNIGHT_ROLLOVER_CHECK will be...
`( 0 != 0 ? update_midnight_rollover() : midnight_rollovers )`

Either way (if it's 1 second past midnight or 0 or anything) this will return 0 because in the former it will compare some positive value to rollovercheck_last_timeofday and that can't be true so it will return midnight_rollovers, which will always be 0 because the only place it's incremented is impossible to ever trigger as rollvercheck_last_timeofday will always be 0 and world.timeofday will never be less than 0.

So this breaks the monotonic-ness of this. It will jump from 846000 to 0 at the GMT date boundary. Which will mean that shift durations will suddenly become negative, and shifts will last for who-knows-how-long.

2021-07-07 19:05 UTC, MarinaGryphon commented
```
/proc/update_midnight_rollover()
	if (world.timeofday < rollovercheck_last_timeofday) //TIME IS GOING BACKWARDS!
		midnight_rollovers += 1
	rollovercheck_last_timeofday = world.timeofday
	return midnight_rollovers
```
Aurora's proc, to show proper functionality.

2021-07-08 12:36 UTC, MarinaGryphon commented
Tested a midnight rollover, autocall works now. Went from 11:30->5:28 (where I saw the hour-left warning)->5:30 tram call with no issues.

2021-07-09 15:41 UTC, Arokha approved these changes
I guess this is technically monotonic now, but I feel compelled to point out that it wouldn't be accurate in the case of waiting more than 1 day between checks. Waiting 24 hours and 1 minute between checks (because it won't have updated rollovercheck_last_timeofday in over 24 hours) will only have increased by one minute, no rollover, and you'll get a difference of 1 minute despite being 24h01m difference.

It doesn't really matter in our case, I guess. Just being PEDANTIC.

2021-07-09 15:53 UTC, merged

2021-08-14 18:47 UTC, Verkister commented
![kuva](https://user-images.githubusercontent.com/13697337/129457289-382d55c8-5461-4c3f-bad6-37e6998fe199.png)
Might be causing this kinda thingy to happen. Real date still 14th and round duration 1:20. insta-called transfer just 50 minutes into the round

2021-08-14 19:00 UTC, Verkister commented
Also to add to the above, it flipped the date on the **noon** station time. We use 24h clock here, not 12

2021-08-14 21:27 UTC, Verkister commented
I just realized this PR doesn't sync the round time with the real time, but instead it syncs the round **_duration_**, which isn't even supposed to be synced to anything, only counting time since round start

2021-08-15 03:30 UTC, MarinaGryphon commented
> I just realized this PR doesn't sync the round time with the real time, but instead it syncs the round **_duration_**, which isn't even supposed to be synced to anything, only counting time since round start

yes, it uses real time since round start rather than byond ticks since round start, which means it ignores time dilation.