Makes fuzzycuffs easier to get out of
VOREStation/VOREStation pull request #11797
Opened 2021-11-07 22:56 UTC by R3dtail

Was messing around in game with them and fuzzycuffs have the same breakout timer as normal cuffs.  They're toys, that doesn't seem 'reasonable' , that they're the same as proper handcuffs.  So this gives them a significantly reduced breakout timer.   10 seconds? Seems reasonable for toys.

2021-11-07 22:59 UTC, Very-Soft requested changes
You'll want to do something like a 
//VOREStation Edit
comment on this in case polaris changes anything with this file, so we won't lose track of what edits are ours~

2021-11-07 23:08 UTC, R3dtail commented
> You'll want to do something like a //VOREStation Edit comment on this in case polaris changes anything with this file, so we won't lose track of what edits are ours~

Sorry, can do, I was just going off of what i was told in discord, I'm flying by the seat of my pants and don't know what I'm doing

2021-11-07 23:40 UTC, Screemonster commented
if anything you kinda _want_ a decent timer on them for a scene since it gives your partner time to notice you resisting out and do something about it while they're typing their posts though

2021-11-07 23:53 UTC, R3dtail commented
> if anything you kinda _want_ a decent timer on them for a scene since it gives your partner time to notice you resisting out and do something about it while they're typing their posts though

That's fair , I was just looking at it from the view point of if someone actually wanted them to not get out, they'd use something more significant than toy cuffs.  and cable cuffs are even more plentiful to get  and those are the go-to "use these if you have nothing else".  Uh- I just went with a low number that was less than cable cuffs.  Y'all are the smarter more familiar people, I'll do whatever number you want.  I'd think ten seconds would be enough to click on someone to move them a bit to keep from wiggling free, but that's just like my opinion.

2021-11-08 04:19 UTC, Very-Soft commented
10 seconds is still a long time to interrupt someone, so fine imo!

2021-11-08 04:19 UTC, merged