Makes NIFs not get automatically lost (hopefully)
VOREStation/VOREStation pull request #11944
Opened 2021-12-01 11:07 UTC by Heroman3003

Makes it so that instead of erasing NIF from savefile and re-saving them later, NIFs only get their savefile durability reduced. This is still minorly punishing for not backing up, but not nearly as harshly as full on deletion. Eases job for admins too.

Properly backed up people will have these durability changes overridden anyway, so that won't cause issues, and if you leave round after extracting a NIF, well, it will also be overridden with nothingness. So this should only affect situations where NIF just disappears.

2021-12-02 05:32 UTC, Arokha commented
This makes it so people who don't get an implant have infinite durability between rounds, doesn't it?

2021-12-02 05:58 UTC, Heroman3003 commented
> This makes it so people who don't get an implant have infinite durability between rounds, doesn't it? EDIT: As in, there's nothing to update the savefile with durability after installing software, if they don't have an implant

NIF is still saved by those people when round ends or they use cryo (or equivalent). Unless they specifically somehow every round die without having a backup, they cannot keep avoiding it saving. Also, that's why the new punishment for 'dying without implant' is loss of about 10-15 durability, its specifically to prevent infinite NIF use being a possible exploit.

2021-12-02 06:15 UTC, Arokha commented
> Unless they specifically somehow every round die without having a backup, they cannot keep avoiding it saving

If this were another server I'd consider that rare but that's the goal of some people here, lol.

It should probably save whenever durability changes, honestly, instead of just at certain times.

2021-12-22 13:47 UTC, Very-Soft requested changes
Pls do the thing Aro suggested. It should just save durability when it changes tbh!

2021-12-25 19:59 UTC, Heroman3003 commented
Done. NIF now should save every time durability changes (assuming its inside a human when it happens).

Also adds unified proc for repair of NIF to facillitate that; and removes the 'alternate punishment' (along with punishments altogether).

2022-01-08 17:39 UTC, merged