Reworks trash pile pool chances
VOREStation/VOREStation pull request #11957
Opened 2021-12-04 05:08 UTC by Heroman3003

This is definitely far from 'complete' version and will probably go some revisions based on staff and player feedback, but, well, it had to be done at some point. Main intent of PR is to finally cut away all the 'useless' stuff from the trash pile pools, making them less of a 'losable' lottery, to accomodate map layouts that use few sparing trash piles better (such as SD).

Currently it removes a lot of Alpha pool items, while reworking meaning of pools themselves.

Alpha pool is now meant to be 'legal, practical, minor' items pool. It contains stuff like power cells, broken emags, welding masks, and on more rare end, pizza vouchers, cabin capsule, THE GLOVES.
Beta pool is now meant to be 'scene-focused' items pool. It contains stuff like sizeguns, fuzzy cuffs, amorphorovir vials, sleevemate, bodysnatcher, etc. Also includes latex maid dress and HYPER jumpsuit.
Original Gamma pool as it was before is untouched, but is now renamed into Delta pool. Works same way, contains same stuff, no change.
New Gamma pool is illegal stuff. Knives, regular cuffs, drugs, syndie devices fall into that pool.

Pool chances are: 50 for Alpha, 30 for Beta, 19 for Gamma and 1 for Delta.

Ultimately, primary intent is for trash piles to be, ironically, less trashy and more reliable in the smaller amounts they are present now without removing RNG chances or adding pity timers or whatnot. Just culling the useless junk like clothes, very generic and easily producable items, etc.

2021-12-04 07:54 UTC, Very-Soft commented
I don't like the way the different pools are weighted, and I don't like a lot of the things you removed from the lists.

2021-12-04 08:11 UTC, Heroman3003 commented
Most of removed things fall into category of being extremely trivial to obtain items, or minor clothing, or basically some loadout stuff, all of which I think isn't that important to most players. I did consider additional option of "trash pile can be searched a few times, one time giving item from the proposed pools with proposed chances, and all the other times giving trivial 'useless' items such as baseballs, clothes, broken components, minor things, etc". But I thought that'd be a counterintuitive addition relative to ways trash piles work right now and would take a while for playerbase to adapt.

2021-12-04 08:57 UTC, Heroman3003 commented
While this wasn't intentional result while I was pruning the lists, I ran some numbers now and this proposed listing I made works out somewhat nicely if we talk about pure chance/balance stuff of items kept and the likelyhood of overall finding 'any of those'

Tether had 62 trash piles in final revision, while Stellar Delight has 19.  That's about 30% of Tether's trash pile amount.

Now if we take individual chances of all items that this PR kept in the pools as they are right now on live, include pool chances in the equation, and add them up, we get that we get that the chance those any of those specific items would get found.... about 30% of the time. So technically this does not making 'finding one of the items kept' more likely. Now proportions those items have within said suggested pools are undoubtedly way, way screwier and going over them individually is way too complicated, but I just wanted to point out that this does not make 'finding these cool things' on the overall of items listed particularly highly likelier, relative to Tether's trash pile amount.

2021-12-06 01:41 UTC, Novacat requested changes

2021-12-06 01:41 UTC, Novacat commented on code/game/objects/structures/trash_pile_vr.dm
> +					prob(1);/obj/item/device/survivalcapsule/popcabin)
This should probably be a beta item.

2021-12-06 01:41 UTC, Novacat commented on code/game/objects/structures/trash_pile_vr.dm
> +					prob(1);/obj/item/clothing/suit/storage/vest/heavy/merc,
This should probably be a gamma item

2021-12-06 01:41 UTC, Novacat commented on code/game/objects/structures/trash_pile_vr.dm
> +					prob(2);/obj/item/clothing/shoes/syndigaloshes,
This can probably be bumped up to Alpha, since if I recall correctly these are just brown shoes which are anti-slip.

2021-12-09 01:13 UTC, Very-Soft commented
I'll look over and test this more soon.

2022-02-06 14:07 UTC, Very-Soft commented
I just really don't like this and want to think about a better solution, especially since we're starting a kind of faux rotation.

2022-02-06 14:07 UTC, closed without merging