re-re-EnerGen Batteries
VOREStation/VOREStation pull request #12798
Opened 2022-04-19 04:03 UTC by GhostActual

Blame Chomp. They made me do it. I swear.

2022-04-19 07:20 UTC, Cyantime commented
This is adding cells that fit in energy weapons with twice the charge of a normal weapon cell, for negligible material cost.
The "super" cell also seems to be an identical copy of the weapon cell, but cheaper for some reason?

2022-04-19 20:14 UTC, GhostActual commented
> This is adding cells that fit in energy weapons with twice the charge of a normal weapon cell, for negligible material cost. The "advanced" cell also seems to be an identical copy of the weapon cell, but cheaper for some reason?

A-ha, nope, none of the new cells fit into weapons, they all fall under the 'device' category. This means that they only fit devices, not weapons. In order for them to fit they'd need `/weapon` added to their path.

`/obj/item/weapon/cell/device/weapon` is the weapon cell while `/obj/item/weapon/cell/device/advanced` is a device cell and so on.

2022-04-19 20:27 UTC, GhostActual commented
I stand corrected, why is this a thing

2022-04-19 20:37 UTC, Cyantime commented
The entire "device" subtype is for small form factor things, weapons, flashlights, etc. The practice laser spawns with a normal device cell, as an example of a weapon that doesn't use or need the full capacity of a weapon cell.

2022-04-19 20:43 UTC, GhostActual commented
Still, it's an easy fix nonetheless

2022-04-19 20:56 UTC, Cyantime commented
Should it though? Most device cell-using things use little amounts of power, and the normal 480 charge cell is enough for them with reasonable recharging now and then, and if you can get ahold of a weapon cell you can use that to extend their use a ton. Adding a bunch of "device cell but a billion power" feels like needless power creep.

2022-04-19 21:12 UTC, GhostActual commented
If that was really an issue then Chomp wouldn't have ported it. It only adds two more cells to research, both of which only increase the shots of a standard laser weapon by five and ten respectively. That doesn't seem so cheese to me. The only one that's "device cell but a billion power" is the `infinite device cell` and that's an admeme only spawn item like the `infinite power cell`.

2022-04-19 21:16 UTC, GhostActual commented
If you're really worried about the cheese I'll also pull the material requirements to create the cells

2022-04-19 21:25 UTC, GhostActual commented
Better still, the code for energy guns is built to where `accept_cell_type` is a var that can be altered so I can make weapon cells only work with weapons and device cells only work with practice weapons if I wanted to travel down the rabbit hole.

2022-04-20 13:37 UTC, Rykka-Stormheart requested changes
Forgotten map swap in .dme

2022-04-20 22:52 UTC, Very-Soft commented on vorestation.dme
> +#include "maps\stellardelight\stellar_delight.dm"
The map is actually presently on the stellar delight. I assume that this branch was made when we were on the tether and has since been corrected.

2022-04-26 21:59 UTC, Novacat reviewed
Since device cells can be slotted into weapons now, this is going to need a big think since weapon power cells with 150%-200% is going to be a substantial change.

2022-04-26 22:16 UTC, Novacat requested changes
Some issues I immediately see off the bat:

- Some devices are coded to use /weapon cell subtype and will not slot regular device cells at all. This PR will make it rather confusing and I can see issues arising in the future of people trying to slot non /weapon cells into these devices.
- 3600/4800 is going to be a substantial buff to magazine-loaded energy weapons. I am kind of iffy on this. I know void cells exist but at least they are kind of hard to get.

My personal recommendations:
- Keep the weapon/device split.
- Add upgraded versions of the device and weapon power cells. The upgraded device cell can hold 960 charge, upgraded weapon cell can hold 3600. Upgraded device cells are fairly cheap/easy to make in science. Upgraded weapon cells require some rare resources and high research. Diamond-tier, at the minimum.

2022-04-26 22:35 UTC, closed without merging