[WIP] Food Synthisizers!
VOREStation/VOREStation pull request #13020
Opened 2022-05-29 13:24 UTC by Poojawa

It's ya sune, back on their bullshit with another complex but hopefully helpful new machine for overnight shifts and food preferences!

CODE BOUNTY: I will literally paypal someone $20 to get the tgui menu working. The panel shows up, but the example recipes do not. Code was mainly snagged from an autolathe, so that was my example for categories, 'hidden' items, and eventually will have voice-activated commands.

I would like to have a bar/% for the cartridge filling wherever it might fit. yet look nicely

Can negotiate more / maybe an art commission thing together idk. I just cannot into UIX at all. lmfao.

A bonus $20 to getting crewmember icons to be pulled from datacore without lag. It must be done only by people who have opted in to a prescan or a scan on station. There is likely to be an additional consent check that is opt-in as default as well, but that is not UI related. 

Basic replicator machine sprite nabbed from Deep Space 13, which is defunct. I made the screen animations, the panel layer, and the adapted canisters that also can be mounted within.

![](https://i.gyazo.com/2103945d3802026a3fe4358a15a7e9b1.gif)

![](https://i.gyazo.com/78bfbdd4753fb22944c9bca1199f8c43.gif)

![](https://i.gyazo.com/6550cb068dd7bc6e9501bcacf99b2187.png)

So there's rounds where there is no chef. 

### This machine does not replace the chef in any way, except the absence of a chef. 

Ok? Ok.

This machine ~~when finished~~ synthesizes a generic, printed block of 1 unit Nutriment. It has no allergy properties and will always give an aftertaste of blandness. 

However, the special notion of this machine is the fact that it will replicate any common food or drink item's looks and (If the food item possesses it) their flavoring. But the replication is merely for people allergic to dairy to be able to eat "Ice Cream". There may also be special functions, should one take a looksie and have experience working with wires. (hint hint)

Science can upgrade the machine, Improving scanners improves how fast the machine will print a chosen food item, improving manipulators grants more nutriment per printing, Rank 5 = ~2s printing, and 5 nutriment per food item. So science has a reason to do something helpful for the masses if they so choose. Most chef products *start* at 3 and scale up significantly with recipes and added ingredient quality. 

The synthesizers have "Synthesizer cartridge" fitted within them. They contain a reagent that cannot be produced locally on station and must be ordered from cargo. This choice is so that it isn't an infinite resource to take advantage of. The normal sized canisters have sufficient supply for 50 meals, whereas the smaller one (intended for use on shuttles/Talon/etc) will only merely do 20. replacing them is as easy as slapping a new can into it!

2022-05-29 16:24 UTC, ItsSelis requested changes
The fixes you asked for.

2022-05-29 16:24 UTC, ItsSelis commented on tgui/packages/tgui/interfaces/synthesizer.js
> +};
```suggestion
```

2022-05-29 16:24 UTC, ItsSelis commented on tgui/packages/tgui/interfaces/synthesizer.js
> +              </Flex.Item>
```suggestion
```

2022-05-29 16:24 UTC, ItsSelis commented on tgui/packages/tgui/interfaces/synthesizer.js
> +                ) || null}
```suggestion
```

2022-05-29 16:24 UTC, ItsSelis commented on tgui/packages/tgui/interfaces/synthesizer.js
> +                  disabled={!canBeMade(recipe, materials, 1)}
```suggestion
```

2022-05-29 16:24 UTC, ItsSelis commented on tgui/packages/tgui/interfaces/synthesizer.js
> +import { createSearch, toTitleCase } from 'common/string';
```suggestion
import { flow } from 'common/fp';
import { filter, sortBy } from 'common/collections';
import { useBackend, useSharedState } from "../backend";
import { Box, Button, Flex, Input, Section, Dropdown } from "../components";
import { Window } from "../layouts";
import { createSearch, toTitleCase } from 'common/string';
```

2022-05-29 16:24 UTC, ItsSelis commented on tgui/packages/tgui/interfaces/synthesizer.js
> +export const synthesizer = (props, context) => {
```suggestion
export const Synthesizer = (props, context) => {
```

2022-05-29 16:24 UTC, ItsSelis commented on code/modules/food/kitchen/cooking_machines/synthesizer_recipes_vr.dm
> +
```suggestion

/datum/category_group/synthesizer/all/New()
	..()

```

2022-05-29 16:24 UTC, ItsSelis commented on code/modules/food/kitchen/cooking_machines/synthesizer_vr.dm
> +	var/static/datum/category_collection/synthesizer_recipes = list()
```suggestion
	var/static/datum/category_collection/synthesizer_recipes/synthesizer_recipes
```

2022-05-29 16:24 UTC, ItsSelis commented on code/modules/food/kitchen/cooking_machines/synthesizer_vr.dm
> +		ui = new(user, src, "synthesizer", name)
```suggestion
		ui = new(user, src, "Synthesizer", name)
```

2022-05-29 16:24 UTC, ItsSelis commented on code/modules/food/kitchen/cooking_machines/synthesizer_vr.dm
> +		for(var/datum/category_item/synthesizer/F in A)
```suggestion
		for(var/datum/category_item/synthesizer/F in A.items)
```

2022-05-29 16:26 UTC, ItsSelis commented
Additionally, the file at `tgui/packages/tgui/interfaces/synthesizer.js` should be renamed into Synthesizer.js (just capitalizing).

2022-06-01 10:09 UTC, Poojawa commented on code/modules/food/kitchen/cooking_machines/synthesizer_vr.dm
> +				var/obj/item/weapon/reagent_containers/food/snacks/food_mimic = new making.path(src)
I'd really like for this food to actually, y'know. copy shit over.

2022-09-23 01:29 UTC, Cameron653 commented
Doing PR cleanup and the last commit to this was 2 months ago and there are conflicts that need to be resolved.

If work is still being done on this PR, feel free to re-open this PR or open a new PR.

2022-09-23 01:29 UTC, closed without merging