[MIRROR-FIX] "Nerfs" Hyperzine
VOREStation/VOREStation pull request #13186
Opened 2022-06-26 23:51 UTC by ItsSelis

This actually buffs Hyperzine (increasing it from 1 to 1.2).

Additional Comment from original PR:
> Also makes psilocybin actually hallucinogenic and removes a very annoying hallucination interaction with airlocks.

This PR should close #12972

2022-06-27 04:03 UTC, Heroman3003 commented
do we even want it changed either way?

2022-06-27 05:58 UTC, ItsSelis commented
> do we even want it changed either way?
> 
> 
> 
> Also this PR seems to include a bunch of new random drugs because why?

Im not sure, I mean, the original PR was still open unlike many of the other ones so I figured it might be a wanted change.

The random drugs were also included in the PR but are most likely due to them being added in the past. I put them into a separate commit to easily remove them again if they are not wanted either.

2022-06-27 06:12 UTC, Heroman3003 commented
> > do we even want it changed either way?
> > Also this PR seems to include a bunch of new random drugs because why?
> 
> Im not sure, I mean, the original PR was still open unlike many of the other ones so I figured it might be a wanted change.
> 
> The random drugs were also included in the PR but are most likely due to them being added in the past. I put them into a separate commit to easily remove them again if they are not wanted either.

The ones that were kept open have had updates to them within last month or were created in that period as new ruling is to close everything older than a month.

2022-06-27 06:56 UTC, ItsSelis commented
> > > do we even want it changed either way?
> > > Also this PR seems to include a bunch of new random drugs because why?
> > 
> > 
> > Im not sure, I mean, the original PR was still open unlike many of the other ones so I figured it might be a wanted change.
> > The random drugs were also included in the PR but are most likely due to them being added in the past. I put them into a separate commit to easily remove them again if they are not wanted either.
> 
> The ones that were kept open have had updates to them within last month or were created in that period as new ruling is to close everything older than a month.

Oh, my bad. Yeah I can remove the random added drugs. Then it can be decided to either merge or close this, depending if it is wanted or not :v

2022-09-21 03:46 UTC, Cameron653 commented
This is able to be merged so a decision should be made instead of having it sit.

2022-09-21 03:58 UTC, TankTheBirb commented
Hyperzine buff is pretty trivial and won't really affect anything. Having the hallucinogen cause hallucinations might be a funny tool here and there. I'd say add it.

2022-09-23 02:20 UTC, Cameron653 requested changes
I'd say to re-add the airlock stun and hit the hyperzine back down to 1.0. Possibly open another PR and see if the hyperzine change is wanted still.

2022-09-23 02:20 UTC, Cameron653 commented on code/game/machinery/doors/airlock.dm
> -		else if(user.hallucination > 50 && prob(10) && src.operating == 0)
From what I've obtained, this should be kept.

And I kind of agree. It's funny.

2022-09-23 02:20 UTC, Cameron653 commented on code/modules/reagents/reagents/drugs.dm
> +	var/drug_strength = 20
This is all good.

2022-09-23 02:20 UTC, Cameron653 commented on code/modules/reagents/reagents/medicine.dm
> +	M.add_chemical_effect(CE_SPEEDBOOST, 1.2)
I personally feel like this is fine but others might disagree. Also hyperzine only really works in increments of 0.5 from what I've been told. I'd say to just bump it back down to only 1.0

2022-10-05 01:50 UTC, Cameron653 commented
Closing due to the above PR being merged.

2022-10-05 01:50 UTC, closed without merging