fluff item spawns now
VOREStation/VOREStation pull request #13973
Opened 2022-10-24 15:51 UTC by TheDavestDave

allowed_roles chaplain doesn't let you spawn in an item if you join as chaplain. I have no idea how to fix that

2022-10-24 17:51 UTC, Runa-Dacino requested changes
Change 

`allowed_roles = "Chaplain`

to 

`allowed_roles = list("Chaplain")`

2022-10-24 19:30 UTC, Very-Soft submitted a review, later dismissed
Fixit, don't just remove the restriction.

2022-10-24 21:32 UTC, Runa-Dacino requested changes

2022-10-24 23:21 UTC, TheDavestDave commented
> Fixit, don't just remove the restriction.

does it still need a job restriction as it's now a sub varriant of a custome with no amour vaules?

2022-10-25 21:05 UTC, Runa-Dacino approved these changes

2022-10-25 21:05 UTC, Runa-Dacino commented on code/modules/client/preference_setup/loadout/loadout_fluffitems_vr.dm
> +	allowed_roles = list("Chaplain")
This should hopefully fix it, and ensure it stays as a chaplain only thing @Very-Soft

2022-10-25 23:22 UTC, merged