Removes ability for research cyborgs to self-upgrade
VOREStation/VOREStation pull request #16593
Opened 2024-11-11 20:01 UTC by DigitalSquirrel95

Port of https://github.com/TS-Rogue-Star/Rogue-Star/pull/335

2024-11-11 20:05 UTC, Kashargul requested changes

2024-11-11 20:05 UTC, Kashargul commented on code/modules/mob/living/silicon/robot/robot.dm
> +					to_chat(user, "<span class='filter_notice'>You are not allowed to manipulate your own lock.</span>")
use of old spans is forbiden

2024-11-11 20:05 UTC, Kashargul commented on code/modules/mob/living/silicon/robot/robot.dm
> +			to_chat(user, "<span class='warning'>You lack the reach to be able to upgrade yourself.</span>")
use of old spans is forbidden

2024-11-12 00:34 UTC, liache commented
This seems like an unnecessary nerf. Do we really want this?

2024-11-15 02:33 UTC, Mattjpark89 commented
On other servers where people are trying to fulfill antag objectives and whatnot, this change makes sense as it increases the difficulty of hacking or modifying a neutral borg (as they can no longer unlock themselves simply by being told to).
On this server though? I don't see a reason for it. Unless it's being abused in some way I can't think of.

2024-11-17 10:54 UTC, merged

2024-11-17 11:40 UTC, SpaceMan-Jim commented
I certainly don't believe this is a very valid issue to justify removing abilities. If there IS a case off a sci unit swapping their module around after upgrading. I'd personally say its a moderation issue than anything else, feels more spite filled considering said individual also wanted to remove the self repair.