Oregrubs
VOREStation/VOREStation pull request #9107
Opened 2020-09-25 16:11 UTC by KillianKirilenko

I decided to try recoloring the solargrub for a laugh, and ended up with something vaguely presentable! So here we are; oregrubs and lavagrubs. ~~What, loot bugs? I have no idea what you're talking about.~~

![image](https://cdn.discordapp.com/attachments/672179670703407104/758773513066119219/unknown.png)

These leathery lithovores and monochrome metallovores can be found slithering around anywhere there's delicious ore to chew on, and can survive just about anywhere (which is to say they spawn in the UD, V4 caves, and V2 surface). They are passive until threatened, at which point they will flee at high velocity - but if you catch them and cut them up, you can extract those minerals! Run them through a gibber to get even more! Lavagrubs contain even more, rarer ores! _D e l i c i o u s._

Grubs are moderately resistant to melee weapons and kinetic accelerators, but fairly weak to ballistics and lasers. They provide a new form of cave life for miners and explorers to encounter that *isn't* automatically hostile! Goodness, look at me finally making good on something that's come up in the exploration channel before. You can even catalogue them for a few points.

Probably needs unique sprites at some point?

2020-09-25 17:21 UTC, KasparoVy commented
Man this is a throwback, I remember old bay mining in space on Para years ago I'd try hunting them down to give the RD a fun new pet.

Awesome

2020-09-27 21:32 UTC, Novacat requested changes
Everything looks fine but I feel like they are a wee bit too common, considering that they spawn pretty much everywhere. I would like for them to be in a more... distinct location. I would recommend Virgo two actually, with maybe a few rare ones showing up in the underdark.

2020-09-27 21:42 UTC, KillianKirilenko commented
Done. Lavagrubs will no longer appear on V4 period, and in general both kinds ought to be a fair bit rarer than they were before.

2020-09-27 21:43 UTC, Novacat approved these changes

2020-09-28 07:30 UTC, merged