Makes pixel shifting work with custom offsets
VOREStation/VOREStation pull request #9374
Opened 2020-11-26 19:52 UTC by Verkister

Pixel shifting now allows mobs with custom offsets to shift themselves 16 pixels from their default offsets instead of point zero. This means that a wide mob can now shift towards left without getting stopped due to being already at -16 at default offset.

2020-11-29 15:32 UTC, Novacat requested changes
Either needs to go upstream or //VOREStation Edit

2020-11-29 16:06 UTC, Verkister commented
The whole part is already inbetween vorestation edit start and end comments

2020-11-30 07:22 UTC, Novacat approved these changes

2020-11-30 07:22 UTC, merged

2020-11-30 07:36 UTC, KasparoVy commented
Lovely, cheers