Add tintable door
VOREStation/VOREStation pull request #9382
Opened 2020-11-29 09:36 UTC by Little-119

![image](https://user-images.githubusercontent.com/4680835/100537914-6621ac80-31fa-11eb-8840-88f0de2cb795.png)
...me, apparently. I mean I wouldn't say I'm excited for them, I'm not entirely sure if adding them is a good idea, but I took that as a challenge. So behold my probably shitty code that I've written at about 3 in the morning. It works and lets more tintable doors be added, at least

I've only added a tintable wide door because that's probably the only one that's going to be used/I don't feel like doing the work to add more right now. Even if I'd personally like a tintable security airlock for reasons.
Problem with this whole concept is that the tinted doors need a separate icon, I can't just change the color like with electrochromic windows. I did a hack job with this by just removing the transparency of the glass part of the sprites (partially because byond's sprite editor is weird and I don't want to figure it out any more), and that was tedious enough

2020-11-29 15:37 UTC, Novacat requested changes

2020-11-29 15:37 UTC, Novacat commented on code/game/machinery/doors/door.dm
> +	// VOREStation Edit End
This could be in door_vr
/obj/machinery/door
	var/tintable = 0
	var/icon_tinted
	var/id_tint

2020-11-29 15:37 UTC, Novacat commented on code/game/machinery/doors/door.dm
> +// VOREStation Edit Start
Likewise moved to door_vr

2020-11-29 15:37 UTC, Novacat commented on code/game/machinery/doors/multi_tile.dm
> +// VOREStation Edit Start
multi_tile_vr

2020-11-30 07:24 UTC, Novacat requested changes
Add multi_tile_vr.dm to the .dme, otherwise that file will not be loaded in.

2020-11-30 22:18 UTC, Wickedtemp commented
<3

2020-11-30 22:42 UTC, Little-119 commented
mlem

2020-11-30 22:47 UTC, KasparoVy commented
The mlemmer of the mlemsdale mlemmadone!

2020-11-30 23:46 UTC, Novacat approved these changes

2020-11-30 23:46 UTC, merged