the big tram now has fancy titanium hull similar to the old one
VOREStation/VOREStation pull request #9567
Opened 2021-01-11 01:43 UTC by Detective-Google

I didn't realize this existed because it had no preview in the editor; but this should hopefully assuage a lot of the concerns people had over the tram not having that distinctive look anymore. 

![image](https://user-images.githubusercontent.com/48196179/104141394-13e8b500-537c-11eb-84d1-423a89a49daa.png)

Still uses reinforced windows because they still match the best.

2021-01-11 04:04 UTC, KillianKirilenko commented
I suggest using the unreinforced version that's clean and doesn't have the hex-mesh over it, might look a little cleaner and more tram-like.

Should just be `/thull/` rather than `/rthull`.

2021-01-11 15:16 UTC, pontifexminimus2 commented
I would like a picture of the titanium hull unreinforced. Because I kind of like the hex mesh.

2021-01-11 22:39 UTC, Ketrai commented
Biggest issue I have is the poor consistenty of the hex mesh. Some are bigger or smaller,  and in some cases the lines even make squares that outright interrupt the pattern. The anti aliasing might be faulty too but I'd have to analyse the overlay up close for that.

2021-01-12 18:26 UTC, KillianKirilenko commented
> Biggest issue I have is the poor consistenty of the hex mesh. Some are bigger or smaller, and in some cases the lines even make squares that outright interrupt the pattern. The anti aliasing might be faulty too but I'd have to analyse the overlay up close for that.

Originally I just thought this was your eyes playing tricks on you, but no. On a closer inspection of the mesh sprite, it basically bulges outwards slightly towards the viewer. I'm not too surprised given that making a seamlessly-repeating hexagonal overlay at that resolution must have been tricky, but it does look a little weird if you look too closely.

2021-01-17 01:55 UTC, Very-Soft commented
Whatever the walls end up looking like, can you shift the tram station expansion on the station side north a bit, so it doesn't cover up the cafe windows?

2021-01-24 22:43 UTC, Novacat requested changes
I agree on unreinforced version of the wall, also Soft's requests.

2021-02-02 16:25 UTC, closed without merging